"""empty message

Revision ID: 307f112832ba
Revises: e4d554e1f1b5
Create Date: 2023-06-15 00:57:23.863240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307f112832ba'
down_revision = 'e4d554e1f1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aditional_comments', sa.String(length=800), nullable=False))
        batch_op.alter_column('project_name',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_constraint('muestra_ubication_image_key', type_='unique')
        batch_op.drop_constraint('muestra_ubication_key', type_='unique')
        batch_op.drop_column('aditional_coments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aditional_coments', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('muestra_ubication_key', ['ubication'])
        batch_op.create_unique_constraint('muestra_ubication_image_key', ['ubication_image'])
        batch_op.alter_column('project_name',
               existing_type=sa.String(length=150),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('aditional_comments')

    # ### end Alembic commands ###
